/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;

import Logica.BLDocumento;
import Logica.BLKey;
import clases.Documentos;
import clases.Keywords;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Smart
 */
public class Documentos_keywords extends javax.swing.JFrame {

    BLDocumento bldocument = new BLDocumento();
    Documentos document = new Documentos();
    BLKey blkey = new BLKey();
    Keywords keyword = new Keywords();
    ArrayList al = new ArrayList();
    ArrayList ale = new ArrayList();
    ArrayList<Documentos> lstestudiante;

    public Documentos_keywords() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Documento segun la palabra en dbpedia");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 21, -1, -1));

        jLabel2.setText("Palabra Clave:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 67, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dbpedia_key", "Acute_respiratory_distress_syndrome", "Adverse_effect", "Aerosol", "Allergic_rhinitis", "Androgen", "Angiotensin-converting_enzyme_2", "Anosmia", "Anticoagulant", "Asthma", "Autopsy", "Ayurveda", "Azithromycin", "BCG_vaccine", "Big_data", "Brain", "Cancer", "Cardiac_arrhythmia", "Cardiovascular_disease", "Care_perspective", "Cauterization", "CD4", "Cell_biology", "Cell_therapy", "Central_nervous_system", "Cerebrovascular_disease", "Chemotherapy", "Chilblains", "China", "China", "Chloroquine", "Clinical_trial", "Coagulation", "Coagulopathy", "Coinfection", "Comorbidity", "Complement_system", "Coronavirus", "Corticosteroid", "CT_scan", "Cytokine", "Cytokine", "Cytokine_storm", "Dentistry", "Diabetes_mellitus", "Diagnosis", "Disease", "Drug_discovery", "Drug_interaction", "Drug_repositioning", "Echocardiography", "Emerging_infectious_disease", "Endotheliitis", "Enzyme_inhibitor", "Epidemic", "Epidemiology", "Ethics", "Fetal_echocardiography", "Genotype", "Geriatrics", "Globalization", "Glucocorticoid", "Growth_factor", "Health_professional", "Herbalism", "Hip_fracture", "Histopathology", "Hydroxychloroquine", "Hyperglycemia", "Immune_system", "Immunology", "Immunotherapy", "Income", "Infection", "Inflammation", "Influenza", "Intelligence", "Intensive_care_medicine", "Kidney", "Lesion", "Medical_imaging", "Medicine", "Middle_East_respiratory_syndrome_coronavirus", "Mortality_rate", "Old_age", "Orthomyxoviridae", "Pandemic", "Reaction_rate", "Thorax" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 131, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Docuemntos"
            }
        ));
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 630, 140));

        jScrollPane2.setViewportView(jTextPane1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 530, 230));

        jButton1.setText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed

        try {
            ListarDoid();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Documentos_keywords.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Documentos_keywords.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Inicio DOCUMENTSKOS = new Inicio();
        DOCUMENTSKOS.setLocationRelativeTo(null);
        this.setVisible(false);
        DOCUMENTSKOS.setVisible(true);

        Documentos_Categorias a = new Documentos_Categorias();
        a.setLocationRelativeTo(null);
        this.setVisible(false);
        a.setVisible(false);

        Documentos_keywords b = new Documentos_keywords();
        b.setLocationRelativeTo(null);
        this.setVisible(false);
        b.setVisible(false);

        Keyword_Categorias c = new Keyword_Categorias();
        c.setLocationRelativeTo(null);
        this.setVisible(false);
        c.setVisible(false);

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     *
     */
    public void ListarDoid() throws ClassNotFoundException, SQLException {
        //Como el método de la BL retorna un ArrayList de la clase Estudiantes
        //Aqui lo recuperamos
        String dbpedia = "'http://dbpedia.org/resource/" + (String) this.jComboBox1.getSelectedItem() + "'";
        keyword.setDbepedia(dbpedia);
        ArrayList<Keywords> lstdoi = blkey.ConsultaLista2(keyword);
        al.clear();
        for (Keywords objeto : lstdoi) {
            String dois = "'" + objeto.getDoi() + "'";
            al.add(dois);

        }
        ale.clear();
        for (int i = 0; i < al.size(); i++) {
            String doiss = (String) al.get(i);
            document.setDoi(doiss);
            lstestudiante = bldocument.ConsultaLista2(document);
            for (Documentos objeto : lstestudiante) {
                String doises = "'" + objeto.getDocumento() + "'";

                ale.add(doises);
            }

        }
        Object columnas[] = {"Nombre del documento"};
        DefaultTableModel modelo = new DefaultTableModel(null, columnas);
        jTable1.setModel(modelo);

        modelo.removeTableModelListener(jTable1);
       Collections.sort(ale);
        for (int i = 0; i < ale.size(); i++) {
            String nombres = (String) ale.get(i);
            String modeloTemp[] = {nombres};
            modelo.addRow(modeloTemp);

        }

    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Documentos_keywords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Documentos_keywords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Documentos_keywords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Documentos_keywords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Documentos_keywords().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
